### PR TITLE
Basic test for Propel Storage Model

### PR DESCRIPTION
**Pull request by liamsorsby**
Basically a slightly modified version of the doctrine model test

### CODE REVIEW

**Comment by liamsorsby** [comment]
@jkabat as stated here is the basic test. Not sure about it though.

**Comment by jkabat** [comment]
@liamsorsby composer in test app forced me to make a branch... are you able to rebase your PR for merging?

**Comment by liamsorsby** [comment]
Yes,

Unfortunately, however I don't have access to the Internet on my laptop in the evenings, I can rebase first thing in the morning. Sorry for the delay!

**Comment by liamsorsby** [comment]
Sorry about the delay, I think that you've probably got past this stage however I think I've rebased the code now.

**Comment by jkabat** [comment]
np. please switch to propel-storage branch a try to create an offsite payment to test the bridge in real world example. in a few hours I should be working on it as well to hunt down the last issues.

**Comment by liamsorsby** [comment]
@jkabat what method are you using in the config, have you opted for the user to create there own model using propel and then link through to that in the config file or is the model going to be pregenerated in the bundle itself?

Also, is there a better way to load the bundles into propel rather then just copying them from a previous project as I wasn't able to get them to load directly using composer using vcs.

**Comment by liamsorsby** [comment]
Also, I have just been reading a few other methods and I was under the impression the schema could have just extended the Model\Token but it looks like with propel it maybe better to create a schema template the user could either use and copy into their own bundle or use their own as per FOS bundle

**Comment by jkabat** [comment]
@liamsorsby Config with custom storage is currently only for testing of bridge implementation. Once the bridge is finished, propel storage would be registered in the payumbundle and everything will be much easier. Also I hope maksim can put the schema somewhere in the payumbundle - that way we can override it anytime we want. Even propelbundle's command "propel:model:build" finally will be usable.

**Comment by jkabat** [comment]
All propel models used in payum has to implement correct interfaces, that's only rule one has to stick to when using custom storage. Maybe everything can be solved by creating proper documentation along with examples of models and schemas.

**Pull request closed without merging**
